# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b2336d132c3fa36718c0ceac1b65b9511715f6e48af06ff419ee9c53ef8ed517fe4eff102fa29b649cebfb2cb603ae894a80a9dce89a287c1e38c9b6240eec3d

test:
  secret_key_base: 89ef29b9026fd1a03be7a443747c173fa3a1b65ce63ec12283d35847b90e30dda9b16fbe9d9ddf363c70dd80a65807ce4ed468886c1bc5acbf14a6d468df2a66

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
